#pragma once
#include <string_view>
#include <string>
#include <cstdint>
#include <sal.h>

namespace pixel_game
{
	enum class CharacterState : uint16_t
	{
		//~ Idle
		IDLE_DOWN        = 1,
		IDLE_LEFT        = 2,
		IDLE_RIGHT       = 3,
		IDLE_UP          = 4,
		IDLE_UP_LEFT     = 5,
		IDLE_UP_RIGHT    = 6,
		IDLE_DOWN_LEFT   = 7,
		IDLE_DOWN_RIGHT  = 8,

		//~ Run
		RUN_DOWN         = 9,
		RUN_LEFT         = 10,
		RUN_RIGHT        = 11,
		RUN_UP           = 12,
		RUN_UP_LEFT      = 13,
		RUN_UP_RIGHT     = 14,
		RUN_DOWN_LEFT    = 15,
		RUN_DOWN_RIGHT   = 16,

		//~ Walk
		WALK_DOWN        = 17,
		WALK_LEFT        = 18,
		WALK_RIGHT       = 19,
		WALK_UP          = 20,
		WALK_UP_LEFT     = 21,
		WALK_UP_RIGHT    = 22,
		WALK_DOWN_LEFT   = 23,
		WALK_DOWN_RIGHT  = 24,

		//~ Dash
		DASH_DOWN        = 25,
		DASH_LEFT        = 26,
		DASH_RIGHT       = 27,
		DASH_UP          = 28,
		DASH_UP_LEFT     = 29,
		DASH_UP_RIGHT    = 30,
		DASH_DOWN_LEFT   = 31,
		DASH_DOWN_RIGHT  = 32,

		//~ Hurt
		HURT_DOWN        = 33,
		HURT_LEFT        = 34,
		HURT_RIGHT       = 35,
		HURT_UP          = 36,
		HURT_UP_LEFT     = 37,
		HURT_UP_RIGHT    = 38,
		HURT_DOWN_LEFT   = 39,
		HURT_DOWN_RIGHT  = 40,

		//~ Die
		DIE_DOWN         = 41,
		DIE_LEFT         = 42,
		DIE_RIGHT        = 43,
		DIE_UP           = 44,
		DIE_UP_LEFT      = 45,
		DIE_UP_RIGHT     = 46,
		DIE_DOWN_LEFT    = 47,
		DIE_DOWN_RIGHT   = 48,

		//~ Attach 1 - 5
		ATTACK1_DOWN       = 49,
		ATTACK1_LEFT       = 50,
		ATTACK1_RIGHT      = 51,
		ATTACK1_UP         = 52,
		ATTACK1_UP_LEFT    = 53,
		ATTACK1_UP_RIGHT   = 54,
		ATTACK1_DOWN_LEFT  = 55,
		ATTACK1_DOWN_RIGHT = 56,

		ATTACK2_DOWN       = 57,
		ATTACK2_LEFT       = 58,
		ATTACK2_RIGHT      = 59,
		ATTACK2_UP         = 60,
		ATTACK2_UP_LEFT    = 61,
		ATTACK2_UP_RIGHT   = 62,
		ATTACK2_DOWN_LEFT  = 63,
		ATTACK2_DOWN_RIGHT = 64,

		ATTACK3_DOWN       = 65,
		ATTACK3_LEFT       = 66,
		ATTACK3_RIGHT      = 67,
		ATTACK3_UP         = 68,
		ATTACK3_UP_LEFT    = 69,
		ATTACK3_UP_RIGHT   = 70,
		ATTACK3_DOWN_LEFT  = 71,
		ATTACK3_DOWN_RIGHT = 72,

		ATTACK4_DOWN       = 73,
		ATTACK4_LEFT       = 74,
		ATTACK4_RIGHT      = 75,
		ATTACK4_UP         = 76,
		ATTACK4_UP_LEFT    = 77,
		ATTACK4_UP_RIGHT   = 78,
		ATTACK4_DOWN_LEFT  = 79,
		ATTACK4_DOWN_RIGHT = 80,

		ATTACK5_DOWN      = 81,
		ATTACK5_LEFT      = 82,
		ATTACK5_RIGHT     = 83,
		ATTACK5_UP        = 84,
		ATTACK5_UP_LEFT   = 85,
		ATTACK5_UP_RIGHT  = 86,
		ATTACK5_DOWN_LEFT = 87,
		ATTACK5_DOWN_RIGHT= 88,
	};


	_NODISCARD _Check_return_
	_CONSTEXPR20 std::string_view ToStringView(_In_ CharacterState state) noexcept
	{
#define CASE_RETURN(x) case CharacterState::x: return #x
		switch (state)
		{
			// Idle
			CASE_RETURN(IDLE_DOWN); CASE_RETURN(IDLE_LEFT); CASE_RETURN(IDLE_RIGHT); CASE_RETURN(IDLE_UP);
			CASE_RETURN(IDLE_UP_LEFT); CASE_RETURN(IDLE_UP_RIGHT); CASE_RETURN(IDLE_DOWN_LEFT); CASE_RETURN(IDLE_DOWN_RIGHT);

			// Run
			CASE_RETURN(RUN_DOWN); CASE_RETURN(RUN_LEFT); CASE_RETURN(RUN_RIGHT); CASE_RETURN(RUN_UP);
			CASE_RETURN(RUN_UP_LEFT); CASE_RETURN(RUN_UP_RIGHT); CASE_RETURN(RUN_DOWN_LEFT); CASE_RETURN(RUN_DOWN_RIGHT);

			// Walk
			CASE_RETURN(WALK_DOWN); CASE_RETURN(WALK_LEFT); CASE_RETURN(WALK_RIGHT); CASE_RETURN(WALK_UP);
			CASE_RETURN(WALK_UP_LEFT); CASE_RETURN(WALK_UP_RIGHT); CASE_RETURN(WALK_DOWN_LEFT); CASE_RETURN(WALK_DOWN_RIGHT);

			// Dash
			CASE_RETURN(DASH_DOWN); CASE_RETURN(DASH_LEFT); CASE_RETURN(DASH_RIGHT); CASE_RETURN(DASH_UP);
			CASE_RETURN(DASH_UP_LEFT); CASE_RETURN(DASH_UP_RIGHT); CASE_RETURN(DASH_DOWN_LEFT); CASE_RETURN(DASH_DOWN_RIGHT);

			// Hurt
			CASE_RETURN(HURT_DOWN); CASE_RETURN(HURT_LEFT); CASE_RETURN(HURT_RIGHT); CASE_RETURN(HURT_UP);
			CASE_RETURN(HURT_UP_LEFT); CASE_RETURN(HURT_UP_RIGHT); CASE_RETURN(HURT_DOWN_LEFT); CASE_RETURN(HURT_DOWN_RIGHT);

			// Die
			CASE_RETURN(DIE_DOWN); CASE_RETURN(DIE_LEFT); CASE_RETURN(DIE_RIGHT); CASE_RETURN(DIE_UP);
			CASE_RETURN(DIE_UP_LEFT); CASE_RETURN(DIE_UP_RIGHT); CASE_RETURN(DIE_DOWN_LEFT); CASE_RETURN(DIE_DOWN_RIGHT);

			// Attacks (1–5)
			CASE_RETURN(ATTACK1_DOWN); CASE_RETURN(ATTACK1_LEFT); CASE_RETURN(ATTACK1_RIGHT); CASE_RETURN(ATTACK1_UP);
			CASE_RETURN(ATTACK1_UP_LEFT); CASE_RETURN(ATTACK1_UP_RIGHT); CASE_RETURN(ATTACK1_DOWN_LEFT); CASE_RETURN(ATTACK1_DOWN_RIGHT);

			CASE_RETURN(ATTACK2_DOWN); CASE_RETURN(ATTACK2_LEFT); CASE_RETURN(ATTACK2_RIGHT); CASE_RETURN(ATTACK2_UP);
			CASE_RETURN(ATTACK2_UP_LEFT); CASE_RETURN(ATTACK2_UP_RIGHT); CASE_RETURN(ATTACK2_DOWN_LEFT); CASE_RETURN(ATTACK2_DOWN_RIGHT);

			CASE_RETURN(ATTACK3_DOWN); CASE_RETURN(ATTACK3_LEFT); CASE_RETURN(ATTACK3_RIGHT); CASE_RETURN(ATTACK3_UP);
			CASE_RETURN(ATTACK3_UP_LEFT); CASE_RETURN(ATTACK3_UP_RIGHT); CASE_RETURN(ATTACK3_DOWN_LEFT); CASE_RETURN(ATTACK3_DOWN_RIGHT);

			CASE_RETURN(ATTACK4_DOWN); CASE_RETURN(ATTACK4_LEFT); CASE_RETURN(ATTACK4_RIGHT); CASE_RETURN(ATTACK4_UP);
			CASE_RETURN(ATTACK4_UP_LEFT); CASE_RETURN(ATTACK4_UP_RIGHT); CASE_RETURN(ATTACK4_DOWN_LEFT); CASE_RETURN(ATTACK4_DOWN_RIGHT);

			CASE_RETURN(ATTACK5_DOWN); CASE_RETURN(ATTACK5_LEFT); CASE_RETURN(ATTACK5_RIGHT); CASE_RETURN(ATTACK5_UP);
			CASE_RETURN(ATTACK5_UP_LEFT); CASE_RETURN(ATTACK5_UP_RIGHT); CASE_RETURN(ATTACK5_DOWN_LEFT); CASE_RETURN(ATTACK5_DOWN_RIGHT);

		default: return "UNKNOWN";
		}
#undef CASE_RETURN
	}

	_NODISCARD _Check_return_
		inline std::string ToString(_In_ CharacterState state)
	{
		return std::string(ToStringView(state));
	}

	_NODISCARD _Check_return_
		_CONSTEXPR20 CharacterState FromString(_In_ std::string_view str) noexcept
	{
#define MATCH_STATE(name) if (str == #name) return CharacterState::name

		MATCH_STATE(IDLE_DOWN); MATCH_STATE(IDLE_LEFT); MATCH_STATE(IDLE_RIGHT); MATCH_STATE(IDLE_UP);
		MATCH_STATE(IDLE_UP_LEFT); MATCH_STATE(IDLE_UP_RIGHT); MATCH_STATE(IDLE_DOWN_LEFT); MATCH_STATE(IDLE_DOWN_RIGHT);

		MATCH_STATE(RUN_DOWN); MATCH_STATE(RUN_LEFT); MATCH_STATE(RUN_RIGHT); MATCH_STATE(RUN_UP);
		MATCH_STATE(RUN_UP_LEFT); MATCH_STATE(RUN_UP_RIGHT); MATCH_STATE(RUN_DOWN_LEFT); MATCH_STATE(RUN_DOWN_RIGHT);

		MATCH_STATE(WALK_DOWN); MATCH_STATE(WALK_LEFT); MATCH_STATE(WALK_RIGHT); MATCH_STATE(WALK_UP);
		MATCH_STATE(WALK_UP_LEFT); MATCH_STATE(WALK_UP_RIGHT); MATCH_STATE(WALK_DOWN_LEFT); MATCH_STATE(WALK_DOWN_RIGHT);

		MATCH_STATE(DASH_DOWN); MATCH_STATE(DASH_LEFT); MATCH_STATE(DASH_RIGHT); MATCH_STATE(DASH_UP);
		MATCH_STATE(DASH_UP_LEFT); MATCH_STATE(DASH_UP_RIGHT); MATCH_STATE(DASH_DOWN_LEFT); MATCH_STATE(DASH_DOWN_RIGHT);

		MATCH_STATE(HURT_DOWN); MATCH_STATE(HURT_LEFT); MATCH_STATE(HURT_RIGHT); MATCH_STATE(HURT_UP);
		MATCH_STATE(HURT_UP_LEFT); MATCH_STATE(HURT_UP_RIGHT); MATCH_STATE(HURT_DOWN_LEFT); MATCH_STATE(HURT_DOWN_RIGHT);

		MATCH_STATE(DIE_DOWN); MATCH_STATE(DIE_LEFT); MATCH_STATE(DIE_RIGHT); MATCH_STATE(DIE_UP);
		MATCH_STATE(DIE_UP_LEFT); MATCH_STATE(DIE_UP_RIGHT); MATCH_STATE(DIE_DOWN_LEFT); MATCH_STATE(DIE_DOWN_RIGHT);

		MATCH_STATE(ATTACK1_DOWN); MATCH_STATE(ATTACK1_LEFT); MATCH_STATE(ATTACK1_RIGHT); MATCH_STATE(ATTACK1_UP);
		MATCH_STATE(ATTACK1_UP_LEFT); MATCH_STATE(ATTACK1_UP_RIGHT); MATCH_STATE(ATTACK1_DOWN_LEFT); MATCH_STATE(ATTACK1_DOWN_RIGHT);

		MATCH_STATE(ATTACK2_DOWN); MATCH_STATE(ATTACK2_LEFT); MATCH_STATE(ATTACK2_RIGHT); MATCH_STATE(ATTACK2_UP);
		MATCH_STATE(ATTACK2_UP_LEFT); MATCH_STATE(ATTACK2_UP_RIGHT); MATCH_STATE(ATTACK2_DOWN_LEFT); MATCH_STATE(ATTACK2_DOWN_RIGHT);

		MATCH_STATE(ATTACK3_DOWN); MATCH_STATE(ATTACK3_LEFT); MATCH_STATE(ATTACK3_RIGHT); MATCH_STATE(ATTACK3_UP);
		MATCH_STATE(ATTACK3_UP_LEFT); MATCH_STATE(ATTACK3_UP_RIGHT); MATCH_STATE(ATTACK3_DOWN_LEFT); MATCH_STATE(ATTACK3_DOWN_RIGHT);

		MATCH_STATE(ATTACK4_DOWN); MATCH_STATE(ATTACK4_LEFT); MATCH_STATE(ATTACK4_RIGHT); MATCH_STATE(ATTACK4_UP);
		MATCH_STATE(ATTACK4_UP_LEFT); MATCH_STATE(ATTACK4_UP_RIGHT); MATCH_STATE(ATTACK4_DOWN_LEFT); MATCH_STATE(ATTACK4_DOWN_RIGHT);

		MATCH_STATE(ATTACK5_DOWN); MATCH_STATE(ATTACK5_LEFT); MATCH_STATE(ATTACK5_RIGHT); MATCH_STATE(ATTACK5_UP);
		MATCH_STATE(ATTACK5_UP_LEFT); MATCH_STATE(ATTACK5_UP_RIGHT); MATCH_STATE(ATTACK5_DOWN_LEFT); MATCH_STATE(ATTACK5_DOWN_RIGHT);

#undef MATCH_STATE
		return static_cast<CharacterState>(0);
	}

	_NODISCARD _Check_return_
	inline CharacterState FromString(_In_ const std::string& s) noexcept { return FromString(std::string_view{ s }); }
	_NODISCARD _Check_return_
	inline CharacterState FromString(_In_z_ const char* s) noexcept { return FromString(std::string_view{ s ? s : "" }); }
}
