@set allusersprofile=c:\programdata
@set appdata=c:\users\u5756151\appdata\roaming
@set chocolateyinstall=c:\programdata\chocolatey
@set chocolateylastpathupdate=134044258029225820
@set clion=c:\program files\jetbrains\clion 2025.2.3\bin
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=wmggame-941227
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files\microsoft visual studio\2022\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set external_include=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\include;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\atlmfc\include;c:\program files\microsoft visual studio\2022\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.26100.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\cppwinrt;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set gcexpconfigusedinsession=3
@set git_lfs_path=c:\program files\git lfs
@set homedrive=c:
@set homepath=\users\u5756151
@set include=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\include;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\atlmfc\include;c:\program files\microsoft visual studio\2022\community\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.26100.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\cppwinrt;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um
@set lib=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\atlmfc\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.26100.0\ucrt\x64;c:\program files (x86)\windows kits\10\\lib\10.0.26100.0\\um\x64
@set libpath=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\atlmfc\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\lib\x64;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.26100.0;c:\program files (x86)\windows kits\10\references\10.0.26100.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\u5756151\appdata\local
@set logonserver=\\wmggame-941227
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=22
@set onedrive=c:\users\u5756151\onedrive
@set os=windows_nt
@set path=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\bin\hostx64\x64;c:\program files\microsoft visual studio\2022\community\common7\ide\vc\vcpackages;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files\microsoft visual studio\2022\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\;c:\program files\microsoft visual studio\2022\community\team tools\diagnosticshub\collector;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\\x64;c:\program files (x86)\windows kits\10\bin\\x64;c:\program files\microsoft visual studio\2022\community\\msbuild\current\bin\amd64;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files\microsoft visual studio\2022\community\common7\ide\;c:\program files\microsoft visual studio\2022\community\common7\tools\;c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files\microsoft visual studio\2022\community\common7\tools;c:\program files\microsoft visual studio\2022\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\nvidia gpu computing toolkit\cuda\v13.0\bin\x64;c:\program files\nvidia gpu computing toolkit\cuda\v13.0\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\git\cmd;c:\program files\nvidia corporation\nvidia app\nvdlisr;c:\programdata\chocolatey\bin;c:\program files\cmake\bin;c:\program files\git lfs;c:\program files\github cli\;c:\program files\nvidia corporation\nsight compute 2025.3.1\;c:\program files\doxygen\bin;c:\users\u5756151\appdata\local\microsoft\windowsapps;c:\users\u5756151\appdata\local\githubdesktop\bin;c:\users\u5756151\appdata\local\programs\microsoft vs code\bin;c:\users\u5756151\.dotnet\tools;c:\users\u5756151\appdata\local\programs\miktex\miktex\bin\x64\;c:\program files\jetbrains\clion 2025.2.3\bin;c:\users\u5756151\appdata\local\microsoft\winget\links;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files\microsoft visual studio\2022\community\common7\ide\vc\linux\bin\connectionmanagerexe;c:\program files\microsoft visual studio\2022\community\vc\vcpkg
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\u5756151\appdata\local\microsoft\visualstudio\17.0_e1095bec\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 170 stepping 4, genuineintel
@set processor_level=6
@set processor_revision=aa04
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=%programfiles%\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files\microsoft visual studio\2022\community\msbuild
@set pvsbuildtools_extensionspath_vs2022=c:\program files\microsoft visual studio\2022\community\msbuild
@set pvsbuildtools_installdir_current=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_installdir_vs2022=c:\program files\microsoft visual studio\2022\community
@set pvsbuildtools_netcoresdkmajorversion=9
@set pvsbuildtools_vctargetspath_current=c:\program files\microsoft visual studio\2022\community\msbuild\microsoft\vc\v170\
@set pvsbuildtools_visualstudioversion_current=17.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\9.0.110\sdks
@set servicehubhostservicebrokerpipename=\\.\pipe\a05d5328-791d-4241-b593-5b8bbc2654e0
@set servicehublogsessionkey=72d99cc3
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\u5756151\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\u5756151\appdata\local\temp
@set ucrtversion=10.0.26100.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdnsdomain=ads.warwick.ac.uk
@set userdomain=ads
@set userdomain_roamingprofile=ads
@set username=u5756151
@set userprofile=c:\users\u5756151
@set vcideinstalldir=c:\program files\microsoft visual studio\2022\community\common7\ide\vc\
@set vcinstalldir=c:\program files\microsoft visual studio\2022\community\vc\
@set vcpkg_root=c:\program files\microsoft visual studio\2022\community\vc\vcpkg
@set vctoolsinstalldir=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\
@set vctoolsredistdir=c:\program files\microsoft visual studio\2022\community\vc\redist\msvc\14.44.35112\
@set vctoolsversion=14.44.35207
@set visualstudiodir=c:\users\u5756151\documents\visual studio 2022
@set visualstudioedition=microsoft visual studio community 2022
@set visualstudioversion=17.0
@set vs170comntools=c:\program files\microsoft visual studio\2022\community\common7\tools\
@set vsappiddir=c:\program files\microsoft visual studio\2022\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=17.14.16
@set vsinstalldir=c:\program files\microsoft visual studio\2022\community\
@set vslang=1033
@set vspermonitordpiawarenessenabled.34912=true
@set vsskuedition=community
@set vs_perf_session_gcheapcount=2
@set webview2_default_background_color=ffffff
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.26100.0;c:\program files (x86)\windows kits\10\references\10.0.26100.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.26100.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.26100.0\
@set windowssdkversion=10.0.26100.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set zes_enable_sysman=1
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files\microsoft visual studio\2022\community\vc\tools\msvc\14.44.35207\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files\microsoft visual studio\2022\community\common7\tools;c:\program files\microsoft visual studio\2022\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\nvidia gpu computing toolkit\cuda\v13.0\bin\x64;c:\program files\nvidia gpu computing toolkit\cuda\v13.0\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\git\cmd;c:\program files\nvidia corporation\nvidia app\nvdlisr;c:\programdata\chocolatey\bin;c:\program files\cmake\bin;c:\program files\git lfs;c:\program files\github cli\;c:\program files\nvidia corporation\nsight compute 2025.3.1\;c:\program files\doxygen\bin;c:\users\u5756151\appdata\local\microsoft\windowsapps;c:\users\u5756151\appdata\local\githubdesktop\bin;c:\users\u5756151\appdata\local\programs\microsoft vs code\bin;c:\users\u5756151\.dotnet\tools;c:\users\u5756151\appdata\local\programs\miktex\miktex\bin\x64\;c:\program files\jetbrains\clion 2025.2.3\bin;c:\users\u5756151\appdata\local\microsoft\winget\links

@call "cl.exe" @"C:\Users\u5756151\Desktop\Workspace\PixelFox\PixelFoxGTests\test.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1